import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    ro: {
        // Navbar
        nav_competitions: "Competiții",
        nav_winners: "Premianți",
        nav_find_tickets: "Caută Bilete",
        nav_faq: "Întrebări",
        nav_signin: "Conectare",
        nav_get_started: "Începe Acum",
        nav_dashboard: "Panou",
        nav_my_tickets: "Biletele Mele",
        nav_wallet: "Portofel",
        nav_admin: "Admin",
        nav_logout: "Deconectare",

        // Homepage
        hero_badge: "Platforma #1 de Competiții din UK",
        hero_title_1: "PARTICIPĂ LA",
        hero_title_2: "COMPETIȚII EXCLUSIVE",
        hero_title_3: "ASTĂZI",
        hero_subtitle: "Cumpără un loc în competițiile noastre pentru mașini de lux, gadgeturi tech, premii în bani și multe altele. Sau participă gratuit prin poștă!",
        hero_enter_now: "Participă Acum",
        hero_view_winners: "Vezi Rezultate",
        stat_prizes: "Premii Oferite",
        stat_winners: "Participanți Fericiți",
        stat_draws: "Extrageri Live",
        section_live_competitions: "Competiții Active",
        section_live_subtitle: "Cumpără un loc sau participă gratuit prin poștă",
        view_all: "Vezi Toate",
        recent_winners: "Câștigători Recenți",
        recent_winners_subtitle: "Alătură-te listei noastre de câștigători fericiți",
        see_all_winners: "Vezi Toți Câștigătorii",
        how_it_works: "Cum Funcționează",
        how_it_works_subtitle: "Pași simpli pentru a participa la competiții",
        step_1_title: "Creează Cont",
        step_1_desc: "Înregistrează-te în câteva secunde cu email sau Google",
        step_2_title: "Cumpără un Loc",
        step_2_desc: "Alege competițiile și rezervă-ți locul",
        step_3_title: "Așteaptă Extragerea",
        step_3_desc: "Extrageri live sau automate",
        step_4_title: "Primești Premiul",
        step_4_desc: "Premiul ajunge direct la tine!",
        trust_secure: "Plăți Securizate",
        trust_verified: "Rezultate Verificate",
        trust_uk: "Înregistrat în UK",
        trust_instant: "Livrare Rapidă",
        cta_ready: "Pregătit să",
        cta_win_big: "Participi",
        cta_join: "Alătură-te miilor de participanți și începe aventura ta astăzi!",
        cta_start: "Începe Acum",
        
        // Live Section
        live_now: "LIVE ACUM",
        live_section_title: "Suntem LIVE!",
        live_section_desc: "Urmărește-ne live pe TikTok pentru extrageri și surprize",
        watch_live: "Urmărește LIVE",
        tiktok_follow: "Urmărește-ne pe TikTok",

        // Competitions
        all_competitions: "Toate Competițiile",
        all_competitions_subtitle: "Răsfoiește toate competițiile disponibile și participă pentru șansa de a câștiga",
        filter_status: "Status",
        filter_all_status: "Toate",
        filter_active: "Active",
        filter_completed: "Încheiate",
        filter_type: "Tip",
        filter_all_types: "Toate Tipurile",
        filter_instant_win: "Câștig Instant",
        filter_classic: "Clasic",
        ticket_price: "Preț Bilet",
        tickets_left: "Bilete Rămase",
        tickets_sold: "vândute",
        tickets_total: "total",
        no_competitions: "Nu Există Competiții",
        no_competitions_subtitle: "Revino în curând pentru premii captivante!",
        clear_filters: "Șterge Filtre",
        badge_instant_win: "Câștig Instant",
        badge_classic: "Tragere Clasică",
        badge_ended: "Încheiat",
        winning_ticket: "Bilet Câștigător",

        // Competition Detail
        back_to_competitions: "Înapoi la Competiții",
        prize: "Premiu",
        tickets_sold_label: "Bilete Vândute",
        tickets_remaining: "bilete rămase",
        winner: "Câștigător",
        competition_ended: "Această competiție s-a încheiat",
        select_quantity: "Selectează Cantitatea",
        balance: "Sold",
        total_cost: "Cost Total",
        buy_tickets: "Rezervă Loc",
        ticket: "Bilet",
        tickets: "Bilete",
        sign_in_to_purchase: "Conectează-te pentru a Cumpăra",
        insufficient_balance: "Sold insuficient.",
        add_funds: "Adaugă fonduri",
        competition_type_instant: "Câștigătorul este extras automat când toate biletele sunt vândute",
        competition_type_classic: "Câștigătorul este extras manual de admin",
        purchase_success: "Achiziție Reușită!",
        your_ticket_numbers: "Numerele tale de bilet:",
        buy_more: "Rezervă Mai Multe",
        view_my_tickets: "Vezi Biletele Mele",
        you_purchased: "Ai cumpărat",
        
        // Qualification Question
        qualification_question: "Întrebare de Calificare",
        qualification_subtitle: "Răspunde corect pentru a continua",
        incorrect_answer: "Răspuns incorect. Te rog să încerci din nou.",
        select_answer: "Selectează răspunsul",
        
        // Postal Entry
        postal_entry_title: "Intrare Gratuită prin Poștă",
        postal_entry_subtitle: "Conform legislației UK, poți participa gratuit prin poștă",
        postal_how_to: "Cum să participi gratuit:",
        postal_write: "Scrie pe o foaie sau carte poștală:",
        postal_send_to: "Trimite la adresa:",
        postal_note: "O intrare poștală = 1 bilet. Max. 1 intrare poștală per competiție.",
        postal_deadline: "Termenul limită: înainte de încheierea competiției",
        
        // Payment options
        payment_method: "Metodă de Plată",
        pay_with_wallet: "Plătește din Portofel",
        pay_with_card: "Plătește cu Cardul (Viva)",
        wallet_balance_label: "Sold Portofel",
        processing: "Se procesează...",
        redirect_to_payment: "Vei fi redirecționat către pagina de plată Viva",

        // Dashboard
        welcome: "Bine ai venit",
        dashboard_subtitle: "Gestionează biletele, portofelul și istoricul",
        your_balance: "Soldul Tău",
        add: "Adaugă",
        tab_overview: "Prezentare",
        tab_tickets: "Biletele Mele",
        tab_wallet: "Portofel",
        tab_history: "Istoric",
        total_tickets: "Total Bilete",
        competitions_entered: "Competiții",
        transactions_count: "Tranzacții",
        browse_competitions: "Răsfoiește Competițiile",
        browse_desc: "Intră în competiții captivante și câștigă premii",
        add_funds_title: "Adaugă Fonduri",
        add_funds_desc: "Depune bani în portofel",
        recent_activity: "Activitate Recentă",
        no_tickets: "Niciun Bilet Încă",
        no_tickets_desc: "Rezervă un loc pentru a participa la competiții",
        view_competition: "Vezi Competiția",
        available_balance: "Sold Disponibil",
        payment_methods: "Metode de Plată",
        viva_payments: "Viva Payments",
        secure_card: "Plăți securizate cu cardul",
        payment_info: "Toate plățile sunt procesate în siguranță prin Viva Payments. Nu stocăm niciodată datele cardului tău.",
        no_history: "Niciun Istoric",
        no_history_desc: "Istoricul tranzacțiilor va apărea aici",
        date: "Data",
        type: "Tip",
        description: "Descriere",
        status: "Status",
        amount: "Sumă",
        deposit_title: "Adaugă Fonduri",
        deposit_desc: "Depune bani în portofel folosind Viva Payments",
        deposit_amount: "Sumă (RON)",
        cancel: "Anulează",
        proceed_to_payment: "Continuă la Plată",
        min_deposit: "Depunerea minimă este 1 RON",

        // Winners
        verified_winners: "Rezultate Verificate",
        our_winners: "Premianții Noștri",
        winners_subtitle: "Oameni reali care au primit premii reale. Tu poți fi următorul!",
        no_winners: "Niciun Premiant Încă",
        no_winners_desc: "Fii primul premiant! Participă la competițiile noastre acum.",
        won_on: "Premiat pe",
        prize_won: "Premiu Primit",
        instant_win_badge: "Câștig Instant",
        live_draw_badge: "Extragere Live",
        auto_badge: "Auto",
        manual_badge: "Manual",
        verified_transparent: "Verificat & Transparent",
        verified_desc: "Toți câștigătorii noștri sunt verificați și extrași corect. Pentru competițiile instant win, câștigătorii sunt selectați automat când toate biletele sunt vândute. Pentru extragerile clasice, câștigătorii sunt selectați folosind un generator de numere aleatorii.",

        // Search
        public_search: "Căutare Publică",
        find_tickets: "Caută Bilete",
        search_subtitle: "Caută biletele oricărui utilizator după username. Vezi la ce competiții au participat.",
        enter_username: "Introdu username...",
        search: "Caută",
        user_not_found: "Utilizator Negăsit",
        user_not_found_desc: "Niciun utilizator găsit cu acest username. Verifică ortografia și încearcă din nou.",
        no_tickets_purchased: "Acest utilizator nu a cumpărat niciun bilet încă.",
        in_competitions: "în",

        // FAQ
        help_center: "Centru de Ajutor",
        faq_title: "Întrebări Frecvente",
        faq_subtitle: "Găsește răspunsuri la întrebările comune despre platforma noastră de competiții",
        still_questions: "Încă ai întrebări?",
        support_here: "Echipa noastră de suport este aici să te ajute",
        faq_1_q: "Cum particip la o competiție?",
        faq_1_a: "Creează un cont, adaugă fonduri în portofel folosind sistemul nostru securizat Viva, apoi răsfoiește competițiile și cumpără bilete pentru orice competiție dorești. Fiecare bilet îți oferă o șansă de câștig!",
        faq_2_q: "Care sunt tipurile diferite de competiții?",
        faq_2_a: "Oferim două tipuri de competiții: 1) Câștig Instant - unde câștigătorul este extras automat când toate biletele sunt vândute (100% capacitate), și 2) Tragere Clasică - unde competiția este încheiată manual și un câștigător este extras în orice moment de către admin.",
        faq_3_q: "Cum sunt selectați câștigătorii?",
        faq_3_a: "Pentru competițiile Câștig Instant, când toate biletele sunt vândute, sistemul nostru selectează automat și aleatoriu un număr de bilet câștigător. Pentru tragerile clasice, câștigătorii sunt selectați folosind un generator certificat de numere aleatorii când adminul încheie competiția.",
        faq_4_q: "Cum adaug fonduri în portofel?",
        faq_4_a: "Mergi la Panou > secțiunea Portofel și apasă 'Adaugă Fonduri'. Vei fi redirecționat către furnizorul nostru securizat de plăți (Viva Payments) unde poți plăti cu cardul de credit/debit. Fondurile sunt de obicei creditate instant.",
        faq_5_q: "Cum aflu dacă am câștigat?",
        faq_5_a: "Câștigătorii sunt afișați pe pagina noastră de Câștigători imediat după extragere. Poți verifica și biletele cumpărate în Panou și să le compari cu numărul biletului câștigător afișat pe fiecare competiție încheiată.",
        faq_6_q: "Cum îmi revendic premiul?",
        faq_6_a: "Odată ce câștigi, te vom contacta prin adresa de email înregistrată în 24-48 de ore cu instrucțiuni despre cum să îți revendici premiul. Te rugăm să te asiguri că adresa ta de email este corectă și verifică folderul spam.",
        faq_7_q: "Pot vedea biletele după achiziție?",
        faq_7_a: "Da! Toate biletele cumpărate sunt vizibile în Panou la 'Biletele Mele'. Poți căuta și biletele oricărui utilizator folosind funcția noastră de căutare publică.",
        faq_8_q: "Există opțiune de intrare gratuită?",
        faq_8_a: "Da, legislația UK ne cere să oferim o cale gratuită de intrare prin poștă. Te rugăm să consulți pagina noastră de Termeni și Condiții pentru detalii despre cum să participi gratuit prin poștă.",
        faq_9_q: "Ce metode de plată acceptați?",
        faq_9_a: "Acceptăm toate cardurile de credit și debit majore (Visa, Mastercard) prin partenerul nostru securizat de plăți Viva Payments. Nu stocăm niciodată datele cardului pe serverele noastre.",
        faq_10_q: "Cum contactez suportul?",
        faq_10_a: "Poți contacta echipa noastră de suport la support@zektrix.uk. Ne propunem să răspundem la toate întrebările în 24 de ore.",

        // Terms
        legal: "Legal",
        terms_title: "Termeni și Condiții",
        terms_updated: "Ultima actualizare",
        terms_intro_title: "1. Introducere",
        terms_intro: "Bine ai venit la Zektrix UK. Acești Termeni și Condiții guvernează utilizarea site-ului nostru și a platformei de competiții situată la zektrix.uk. Prin utilizarea Serviciului nostru, ești de acord să fii obligat de acești Termeni.",
        terms_eligibility_title: "2. Eligibilitate",
        terms_eligibility_1: "Trebuie să ai cel puțin 18 ani pentru a participa la competițiile noastre.",
        terms_eligibility_2: "Trebuie să fii rezident al Regatului Unit.",
        terms_eligibility_3: "Angajații Zektrix UK și membrii familiei lor imediate nu sunt eligibili să participe.",
        terms_eligibility_4: "Este permis doar un cont per persoană.",
        terms_rules_title: "3. Regulile Competiției",
        terms_entry_methods: "3.1 Metode de Intrare:",
        terms_entry_methods_desc: "Intrările pot fi cumpărate prin site-ul nostru folosind sistemul de portofel. Fiecare bilet cumpărat oferă o intrare în competiția specificată.",
        terms_ticket_numbers: "3.2 Numere de Bilet:",
        terms_ticket_numbers_desc: "Numerele de bilet sunt atribuite aleatoriu la momentul achiziției. Fiecare număr este unic în cadrul unei competiții.",
        terms_winner_selection: "3.3 Selectarea Câștigătorului:",
        terms_instant_win_rules: "Competiții Câștig Instant: Câștigătorii sunt selectați automat prin extragere aleatorie când 100% din bilete au fost vândute.",
        terms_classic_rules: "Competiții Tragere Clasică: Câștigătorii sunt selectați prin extragere aleatorie când competiția este închisă de administrator.",
        terms_notification: "3.4 Notificare:",
        terms_notification_desc: "Câștigătorii vor fi notificați prin email în 48 de ore de la extragere și afișați pe pagina noastră de Câștigători.",
        terms_postal_title: "4. Rută Gratuită de Intrare prin Poștă",
        terms_postal_intro: "În conformitate cu legislația UK, oferim o rută gratuită de intrare prin poștă pentru toate competițiile. Pentru a participa gratuit:",
        terms_postal_1: "Scrie numele tău complet, adresa de email, adresa poștală și numele competiției la care dorești să participi pe o carte poștală sau plic sigilat.",
        terms_postal_2: "Trimite-o la: Zektrix UK, Intrare Gratuită, [Adresa va fi furnizată]",
        terms_postal_3: "Fiecare intrare poștală este echivalentă cu o intrare cu bilet plătit.",
        terms_postal_4: "Intrările poștale trebuie primite înainte de încheierea competiției.",
        terms_postal_5: "Maximum o intrare poștală gratuită per persoană per competiție.",
        terms_postal_note: "Intrările poștale gratuite au exact aceeași șansă de câștig ca și intrările plătite.",
        terms_payments_title: "5. Plăți și Portofel",
        terms_payments_1: "Plățile sunt procesate în siguranță prin Viva Payments.",
        terms_payments_2: "Fondurile adăugate în portofel nu sunt rambursabile.",
        terms_payments_3: "Soldul portofelului poate fi folosit doar pentru achiziția biletelor de competiție.",
        terms_payments_4: "Nu stocăm datele cardului de plată pe serverele noastre.",
        terms_prizes_title: "6. Premii",
        terms_prizes_1: "Premiile sunt cele descrise pe pagina fiecărei competiții.",
        terms_prizes_2: "Premiile nu sunt transferabile și nu sunt disponibile alternative în bani dacă nu se specifică altfel.",
        terms_prizes_3: "Câștigătorii trebuie să își revendice premiul în 30 de zile de la notificare.",
        terms_prizes_4: "Ne rezervăm dreptul de a înlocui premiile cu altele de valoare egală sau mai mare.",
        terms_liability_title: "7. Limitarea Răspunderii",
        terms_liability: "În măsura maximă permisă de lege, Zektrix UK nu va fi responsabil pentru nicio daună indirectă, incidentală, specială, consecventă sau punitivă care rezultă din sau se referă la utilizarea Serviciului.",
        terms_privacy_title: "8. Confidențialitate",
        terms_privacy: "Suntem angajați să protejăm confidențialitatea ta. Informațiile personale colectate sunt folosite exclusiv pentru operarea Serviciului și contactarea câștigătorilor. Nu vindem și nu partajăm informațiile tale cu terți, cu excepția cazurilor cerute de lege.",
        terms_changes_title: "9. Modificări ale Termenilor",
        terms_changes: "Ne rezervăm dreptul de a modifica acești Termeni în orice moment. Modificările vor fi efective imediat după publicare. Utilizarea continuă a Serviciului constituie acceptarea Termenilor modificați.",
        terms_contact_title: "10. Contactează-ne",
        terms_contact: "Pentru orice întrebări cu privire la acești Termeni sau Serviciul nostru, te rugăm să ne contactezi la:",
        terms_agreement: "Prin utilizarea Zektrix UK, confirmi că ai citit, înțeles și ești de acord să fii obligat de acești Termeni și Condiții.",

        // Footer
        footer_desc: "Platforma de top din UK pentru competiții online. Câștigă premii uimitoare cu extragerile noastre captivante!",
        footer_quick_links: "Linkuri Rapide",
        footer_all_competitions: "Toate Competițiile",
        footer_recent_winners: "Câștigători Recenți",
        footer_find_tickets: "Caută Biletele Tale",
        footer_legal: "Legal",
        footer_terms: "Termeni și Condiții",
        footer_faq: "Întrebări Frecvente",
        footer_contact: "Contact",
        footer_secure: "Plăți Securizate de Viva",
        footer_rights: "Toate drepturile rezervate.",
        footer_responsible: "18+ | Te rugăm să joci responsabil | Intrare Poștală Gratuită Disponibilă",

        // Login
        welcome_login: "Bine ai venit",
        login_subtitle: "Conectează-te pentru a participa la competiții și a câștiga premii uimitoare",
        tab_signin: "Conectare",
        tab_signup: "Înregistrare",
        email: "Email",
        password: "Parolă",
        username: "Nume utilizator",
        confirm_password: "Confirmă Parola",
        or_continue: "Sau continuă cu",
        continue_google: "Continuă cu Google",
        by_signing: "Prin conectare, ești de acord cu",
        instant_wins: "Câștiguri Instant",
        big_prizes: "Premii Mari",
        easy_deposits: "Depuneri Ușoare",

        // Admin
        admin_panel: "Panou Admin",
        admin_refresh: "Actualizează",
        admin_back: "Panou",
        admin_dashboard: "Prezentare",
        admin_competitions: "Competiții",
        admin_users: "Utilizatori",
        admin_tickets: "Bilete",
        admin_winners: "Câștigători",
        admin_total_users: "Total Utilizatori",
        admin_total_comps: "Competiții",
        admin_active: "Active",
        admin_total_tickets: "Total Bilete",
        admin_manage_comps: "Gestionează Competițiile",
        admin_add_comp: "Adaugă Competiție",
        admin_edit: "Editează",
        admin_delete: "Șterge",
        admin_end: "Încheie",
        admin_draw: "Extrage",
        admin_price: "Preț",
        admin_sold: "Vândute",
        admin_manage_users: "Gestionează Utilizatorii",
        admin_user: "Utilizator",
        admin_role: "Rol",
        admin_actions: "Acțiuni",
        admin_view_tickets: "Vezi Toate Biletele",
        admin_filter_comp: "Filtrează după Competiție",
        admin_all_comps: "Toate Competițiile",
        admin_search_user: "Caută după username",
        admin_click_search: "Apasă Caută pentru a vedea biletele",
        admin_manage_winners: "Gestionează Câștigătorii",
        admin_add_winner: "Adaugă Câștigător Manual",
        admin_edit_comp: "Editează Competiția",
        admin_add_comp_title: "Adaugă Competiție",
        admin_title: "Titlu",
        admin_desc: "Descriere",
        admin_ticket_price: "Preț Bilet (RON)",
        admin_max_tickets: "Bilete Maxime",
        admin_type: "Tip",
        admin_type_instant: "Câștig Instant (extragere auto la 100%)",
        admin_type_classic: "Clasic (extragere manuală)",
        admin_image_url: "URL Imagine",
        admin_prize_desc: "Descriere Premiu",
        admin_create: "Creează",
        admin_update: "Actualizează",
        admin_edit_user: "Editează Utilizator",
        admin_balance_adj: "Ajustare Sold (RON)",
        admin_current: "Curent",
        admin_new_password: "Parolă Nouă (lasă gol pentru a păstra actuala)",
        admin_update_user: "Actualizează Utilizator",
        admin_add_winner_title: "Adaugă Câștigător Manual",
        admin_for_classic: "Doar pentru competiții clasice",
        admin_competition: "Competiție",
        admin_select_comp: "Selectează competiția",
        admin_select_user: "Selectează utilizator",
        admin_ticket_number: "Număr Bilet",
        admin_prize_optional: "Descriere Premiu (opțional)",
        admin_add_winner_btn: "Adaugă Câștigător",

        // Common
        loading: "Se încarcă...",
        error: "Eroare",
        success: "Succes",
        purchased_on: "Cumpărat pe",
    },
    en: {
        // Navbar
        nav_competitions: "Competitions",
        nav_winners: "Results",
        nav_find_tickets: "Find Tickets",
        nav_faq: "FAQ",
        nav_signin: "Sign In",
        nav_get_started: "Get Started",
        nav_dashboard: "Dashboard",
        nav_my_tickets: "My Tickets",
        nav_wallet: "Wallet",
        nav_admin: "Admin Panel",
        nav_logout: "Log Out",

        // Homepage
        hero_badge: "UK's Premier Competition Platform",
        hero_title_1: "JOIN",
        hero_title_2: "EXCLUSIVE",
        hero_title_3: "COMPETITIONS",
        hero_subtitle: "Get your spot in our competitions for luxury cars, tech gadgets, cash prizes and more. Or enter free by post!",
        hero_enter_now: "Enter Now",
        hero_view_winners: "View Results",
        stat_prizes: "Prizes Offered",
        stat_winners: "Happy Participants",
        stat_draws: "Live Draws",
        section_live_competitions: "Live Competitions",
        section_live_subtitle: "Get your spot or enter free by post",
        view_all: "View All",
        recent_winners: "Recent Results",
        recent_winners_subtitle: "Join our growing list of happy participants",
        see_all_winners: "See All Results",
        how_it_works: "How It Works",
        how_it_works_subtitle: "Simple steps to join competitions",
        step_1_title: "Create Account",
        step_1_desc: "Sign up in seconds with email or Google",
        step_2_title: "Get Your Spot",
        step_2_desc: "Choose competitions and reserve your entry",
        step_3_title: "Wait for Draw",
        step_3_desc: "Live or automatic draws",
        step_4_title: "Receive Prize",
        step_4_desc: "Prize delivered directly to you!",
        trust_secure: "Secure Payments",
        trust_verified: "Verified Results",
        trust_uk: "UK Registered",
        trust_instant: "Fast Delivery",
        cta_ready: "Ready to",
        cta_win_big: "Join",
        cta_join: "Join thousands of participants and start your adventure today!",
        cta_start: "Get Started Now",
        
        // Live Section
        live_now: "LIVE NOW",
        live_section_title: "We're LIVE!",
        live_section_desc: "Watch us live on TikTok for draws and surprises",
        watch_live: "Watch LIVE",
        tiktok_follow: "Follow us on TikTok",

        // Competitions
        all_competitions: "All Competitions",
        all_competitions_subtitle: "Browse all available competitions and enter for your chance to win",
        filter_status: "Status",
        filter_all_status: "All Status",
        filter_active: "Active",
        filter_completed: "Completed",
        filter_type: "Type",
        filter_all_types: "All Types",
        filter_instant_win: "Instant Win",
        filter_classic: "Classic Draw",
        ticket_price: "Ticket Price",
        tickets_left: "Tickets Left",
        tickets_sold: "sold",
        tickets_total: "total",
        no_competitions: "No Competitions Found",
        no_competitions_subtitle: "Check back soon for exciting new prizes!",
        clear_filters: "Clear Filters",
        badge_instant_win: "Instant Win",
        badge_classic: "Classic Draw",
        badge_ended: "Ended",
        winning_ticket: "Winning Ticket",

        // Competition Detail
        back_to_competitions: "Back to Competitions",
        prize: "Prize",
        tickets_sold_label: "Tickets Sold",
        tickets_remaining: "tickets remaining",
        winner: "Winner",
        competition_ended: "This competition has ended",
        select_quantity: "Select Quantity",
        balance: "Balance",
        total_cost: "Total Cost",
        buy_tickets: "Reserve Spot",
        ticket: "Ticket",
        tickets: "Tickets",
        sign_in_to_purchase: "Sign In to Purchase",
        insufficient_balance: "Insufficient balance.",
        add_funds: "Add funds",
        competition_type_instant: "Winner is automatically drawn when all tickets are sold",
        competition_type_classic: "Winner is drawn manually by admin",
        purchase_success: "Purchase Successful!",
        your_ticket_numbers: "Your ticket numbers:",
        buy_more: "Reserve More",
        view_my_tickets: "View My Tickets",
        you_purchased: "You've purchased",

        // Qualification Question
        qualification_question: "Qualification Question",
        qualification_subtitle: "Answer correctly to continue",
        incorrect_answer: "Incorrect answer. Please try again.",
        select_answer: "Select your answer",
        
        // Postal Entry
        postal_entry_title: "Free Postal Entry",
        postal_entry_subtitle: "In accordance with UK law, you can enter for free by post",
        postal_how_to: "How to enter for free:",
        postal_write: "Write on a piece of paper or postcard:",
        postal_send_to: "Send to:",
        postal_note: "One postal entry = 1 ticket. Max. 1 postal entry per competition.",
        postal_deadline: "Deadline: before competition closes",

        // Payment options
        payment_method: "Payment Method",
        pay_with_wallet: "Pay from Wallet",
        pay_with_card: "Pay with Card (Viva)",
        wallet_balance_label: "Wallet Balance",
        processing: "Processing...",
        redirect_to_payment: "You will be redirected to Viva payment page",

        // Dashboard
        welcome: "Welcome",
        dashboard_subtitle: "Manage your tickets, wallet, and history",
        your_balance: "Your Balance",
        add: "Add",
        tab_overview: "Overview",
        tab_tickets: "My Tickets",
        tab_wallet: "Wallet",
        tab_history: "History",
        total_tickets: "Total Tickets",
        competitions_entered: "Competitions",
        transactions_count: "Transactions",
        browse_competitions: "Browse Competitions",
        browse_desc: "Enter exciting competitions and win prizes",
        add_funds_title: "Add Funds",
        add_funds_desc: "Deposit money to your wallet",
        recent_activity: "Recent Activity",
        no_tickets: "No Tickets Yet",
        no_tickets_desc: "Purchase tickets to enter competitions",
        view_competition: "View Competition",
        available_balance: "Available Balance",
        payment_methods: "Payment Methods",
        viva_payments: "Viva Payments",
        secure_card: "Secure card payments",
        payment_info: "All payments are processed securely through Viva Payments. We never store your card details.",
        no_history: "No Transaction History",
        no_history_desc: "Your transaction history will appear here",
        date: "Date",
        type: "Type",
        description: "Description",
        status: "Status",
        amount: "Amount",
        deposit_title: "Add Funds",
        deposit_desc: "Deposit money to your wallet using Viva Payments",
        deposit_amount: "Amount (RON)",
        cancel: "Cancel",
        proceed_to_payment: "Proceed to Payment",
        min_deposit: "Minimum deposit is 1 RON",

        // Winners
        verified_winners: "Verified Winners",
        our_winners: "Our Winners",
        winners_subtitle: "Real people winning real prizes. You could be next!",
        no_winners: "No Winners Yet",
        no_winners_desc: "Be the first to win! Enter our competitions now.",
        won_on: "Won on",
        prize_won: "Prize Won",
        instant_win_badge: "Instant Win",
        live_draw_badge: "Live Draw",
        auto_badge: "Auto",
        manual_badge: "Manual",
        verified_transparent: "Verified & Transparent",
        verified_desc: "All our winners are verified and drawn fairly. For instant win competitions, winners are automatically selected when all tickets are sold. For classic draws, winners are selected using a random number generator.",

        // Search
        public_search: "Public Search",
        find_tickets: "Find Tickets",
        search_subtitle: "Search for any user's tickets by their username. View which competitions they've entered.",
        enter_username: "Enter username...",
        search: "Search",
        user_not_found: "User Not Found",
        user_not_found_desc: "No user found with that username. Please check the spelling and try again.",
        no_tickets_purchased: "This user hasn't purchased any tickets yet.",
        in_competitions: "in",

        // FAQ
        help_center: "Help Center",
        faq_title: "Frequently Asked Questions",
        faq_subtitle: "Find answers to common questions about our competition platform",
        still_questions: "Still have questions?",
        support_here: "Our support team is here to help",
        faq_1_q: "How do I enter a competition?",
        faq_1_a: "Simply create an account, add funds to your wallet using our secure Viva payment system, then browse our competitions and purchase tickets for any competition you'd like to enter. Each ticket gives you a chance to win!",
        faq_2_q: "What are the different competition types?",
        faq_2_a: "We offer two types of competitions: 1) Instant Win - where the winner is automatically drawn when all tickets are sold (100% capacity), and 2) Classic Draw - where the competition is ended manually and a winner is drawn at any time by the admin.",
        faq_3_q: "How are winners selected?",
        faq_3_a: "For Instant Win competitions, when all tickets are sold, our system automatically and randomly selects a winning ticket number. For Classic draws, winners are selected using a certified random number generator when the admin ends the competition.",
        faq_4_q: "How do I add funds to my wallet?",
        faq_4_a: "Go to your Dashboard > Wallet section and click 'Add Funds'. You'll be redirected to our secure payment provider (Viva Payments) where you can pay using credit/debit card. Funds are usually credited instantly.",
        faq_5_q: "How do I know if I've won?",
        faq_5_a: "Winners are displayed on our Winners page immediately after the draw. You can also check your purchased tickets in your Dashboard and compare them with the winning ticket number shown on each completed competition.",
        faq_6_q: "How do I claim my prize?",
        faq_6_a: "Once you win, we will contact you via your registered email address within 24-48 hours with instructions on how to claim your prize. Please ensure your email address is correct and check your spam folder.",
        faq_7_q: "Can I see my tickets after purchase?",
        faq_7_a: "Yes! All your purchased tickets are visible in your Dashboard under 'My Tickets'. You can also search for any user's tickets using our public ticket search feature.",
        faq_8_q: "Is there a free entry option?",
        faq_8_a: "Yes, UK law requires us to offer a free postal entry route. Please see our Terms & Conditions page for details on how to enter for free via post.",
        faq_9_q: "What payment methods do you accept?",
        faq_9_a: "We accept all major credit and debit cards (Visa, Mastercard) through our secure payment partner Viva Payments. We do not store any payment card details on our servers.",
        faq_10_q: "How do I contact support?",
        faq_10_a: "You can reach our support team at support@zektrix.uk. We aim to respond to all enquiries within 24 hours.",

        // Terms
        legal: "Legal",
        terms_title: "Terms & Conditions",
        terms_updated: "Last updated",
        terms_intro_title: "1. Introduction",
        terms_intro: "Welcome to Zektrix UK. These Terms and Conditions govern your use of our website and competition platform located at zektrix.uk. By using our Service, you agree to be bound by these Terms.",
        terms_eligibility_title: "2. Eligibility",
        terms_eligibility_1: "You must be at least 18 years of age to participate in our competitions.",
        terms_eligibility_2: "You must be a resident of the United Kingdom.",
        terms_eligibility_3: "Employees of Zektrix UK and their immediate family members are not eligible to enter.",
        terms_eligibility_4: "Only one account per person is permitted.",
        terms_rules_title: "3. Competition Rules",
        terms_entry_methods: "3.1 Entry Methods:",
        terms_entry_methods_desc: "Entries can be purchased through our website using the wallet system. Each ticket purchased gives one entry into the specified competition.",
        terms_ticket_numbers: "3.2 Ticket Numbers:",
        terms_ticket_numbers_desc: "Ticket numbers are randomly assigned at the time of purchase. Each number is unique within a competition.",
        terms_winner_selection: "3.3 Winner Selection:",
        terms_instant_win_rules: "Instant Win Competitions: Winners are automatically selected by random draw when 100% of tickets have been sold.",
        terms_classic_rules: "Classic Draw Competitions: Winners are selected by random draw when the competition is closed by the administrator.",
        terms_notification: "3.4 Notification:",
        terms_notification_desc: "Winners will be notified via email within 48 hours of the draw and displayed on our Winners page.",
        terms_postal_title: "4. Free Postal Entry Route",
        terms_postal_intro: "In accordance with UK law, we offer a free postal entry route for all competitions. To enter for free:",
        terms_postal_1: "Write your full name, email address, postal address, and the competition name you wish to enter on a postcard or sealed envelope.",
        terms_postal_2: "Post it to: Zektrix UK, Free Entry, [Address to be provided]",
        terms_postal_3: "Each postal entry is equivalent to one paid ticket entry.",
        terms_postal_4: "Postal entries must be received before the competition closes.",
        terms_postal_5: "Maximum of one free postal entry per person per competition.",
        terms_postal_note: "Free postal entries have exactly the same chance of winning as paid entries.",
        terms_payments_title: "5. Payments and Wallet",
        terms_payments_1: "Payments are processed securely through Viva Payments.",
        terms_payments_2: "Funds added to your wallet are non-refundable.",
        terms_payments_3: "Wallet balance can only be used to purchase competition tickets.",
        terms_payments_4: "We do not store payment card details on our servers.",
        terms_prizes_title: "6. Prizes",
        terms_prizes_1: "Prizes are as described on each competition page.",
        terms_prizes_2: "Prizes are non-transferable and no cash alternatives are available unless stated.",
        terms_prizes_3: "Winners must claim their prize within 30 days of notification.",
        terms_prizes_4: "We reserve the right to substitute prizes of equal or greater value.",
        terms_liability_title: "7. Limitation of Liability",
        terms_liability: "To the maximum extent permitted by law, Zektrix UK shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the Service.",
        terms_privacy_title: "8. Privacy",
        terms_privacy: "We are committed to protecting your privacy. Personal information collected is used solely for operating the Service and contacting winners. We do not sell or share your information with third parties except as required by law.",
        terms_changes_title: "9. Changes to Terms",
        terms_changes: "We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting. Your continued use of the Service constitutes acceptance of the modified Terms.",
        terms_contact_title: "10. Contact Us",
        terms_contact: "For any questions regarding these Terms or our Service, please contact us at:",
        terms_agreement: "By using Zektrix UK, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.",

        // Footer
        footer_desc: "UK's premier online competition platform. Win amazing prizes with our exciting draws!",
        footer_quick_links: "Quick Links",
        footer_all_competitions: "All Competitions",
        footer_recent_winners: "Recent Winners",
        footer_find_tickets: "Find Your Tickets",
        footer_legal: "Legal",
        footer_terms: "Terms & Conditions",
        footer_faq: "FAQ",
        footer_contact: "Contact",
        footer_secure: "Secure Payments by Viva",
        footer_rights: "All rights reserved.",
        footer_responsible: "18+ | Please gamble responsibly | Free Postal Entry Available",

        // Login
        welcome_login: "Welcome",
        login_subtitle: "Sign in to enter competitions and win amazing prizes",
        tab_signin: "Sign In",
        tab_signup: "Sign Up",
        email: "Email",
        password: "Password",
        username: "Username",
        confirm_password: "Confirm Password",
        or_continue: "Or continue with",
        continue_google: "Continue with Google",
        by_signing: "By signing in, you agree to our",
        instant_wins: "Instant Wins",
        big_prizes: "Big Prizes",
        easy_deposits: "Easy Deposits",

        // Admin (kept in English for admin interface)
        admin_panel: "Admin Panel",
        admin_refresh: "Refresh",
        admin_back: "Dashboard",
        admin_dashboard: "Dashboard",
        admin_competitions: "Competitions",
        admin_users: "Users",
        admin_tickets: "Tickets",
        admin_winners: "Winners",
        admin_total_users: "Total Users",
        admin_total_comps: "Competitions",
        admin_active: "Active",
        admin_total_tickets: "Total Tickets",
        admin_manage_comps: "Manage Competitions",
        admin_add_comp: "Add Competition",
        admin_edit: "Edit",
        admin_delete: "Delete",
        admin_end: "End",
        admin_draw: "Draw",
        admin_price: "Price",
        admin_sold: "Sold",
        admin_manage_users: "Manage Users",
        admin_user: "User",
        admin_role: "Role",
        admin_actions: "Actions",
        admin_view_tickets: "View All Tickets",
        admin_filter_comp: "Filter by Competition",
        admin_all_comps: "All Competitions",
        admin_search_user: "Search by username",
        admin_click_search: "Click Search to view tickets",
        admin_manage_winners: "Manage Winners",
        admin_add_winner: "Add Winner Manually",
        admin_edit_comp: "Edit Competition",
        admin_add_comp_title: "Add Competition",
        admin_title: "Title",
        admin_desc: "Description",
        admin_ticket_price: "Ticket Price (RON)",
        admin_max_tickets: "Max Tickets",
        admin_type: "Type",
        admin_type_instant: "Instant Win (auto draw at 100%)",
        admin_type_classic: "Classic (manual draw)",
        admin_image_url: "Image URL",
        admin_prize_desc: "Prize Description",
        admin_create: "Create",
        admin_update: "Update",
        admin_edit_user: "Edit User",
        admin_balance_adj: "Balance Adjustment (RON)",
        admin_current: "Current",
        admin_new_password: "New Password (leave empty to keep current)",
        admin_update_user: "Update User",
        admin_add_winner_title: "Add Winner Manually",
        admin_for_classic: "For classic competitions only",
        admin_competition: "Competition",
        admin_select_comp: "Select competition",
        admin_select_user: "Select user",
        admin_ticket_number: "Ticket Number",
        admin_prize_optional: "Prize Description (optional)",
        admin_add_winner_btn: "Add Winner",

        // Common
        loading: "Loading...",
        error: "Error",
        success: "Success",
        purchased_on: "Purchased on",
    }
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        return saved || 'ro'; // Romanian by default
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'ro' ? 'en' : 'ro');
    };

    const value = {
        language,
        setLanguage,
        toggleLanguage,
        t,
        isRomanian: language === 'ro'
    };

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export default LanguageContext;
